### PR TITLE
feat: Update GUI with nested drop-down, suggestions link, synced progress bar, globals, auto-open download directory

### PR DESCRIPTION
**Pull request by ltfschoen**

### CODE REVIEW

**Comment by nikhilkumarsingh** [comment]
I really appreciate your efforts @ltfschoen . I had been a bit busy so  couldn't see your code.
I will try to understand and merge your code by tomorrow.

**Comment by ltfschoen** [comment]
Thanks. I did a proper rebase with your upstream and I'm pretty confident all the bugs are resolved.
The only problem I have is that even after running `pip install ctdl` and `pip install -U .`, when I try to run a search from the command line with `ctdl -f pdf cat` it gives me error `ModuleNotFoundError: No module named 'downloader'` (which relates to [this line in ctdl.py](https://github.com/nikhilkumarsingh/content-downloader/blob/master/ctdl/ctdl.py#L16)), and even if I rename that line to give it a `.` prefix (i.e. `from .downloader import download_series, download_parallel`) it still gives the same error. It works if I instead run `python ctdl/ctdl.py -f pdf cat`.
So I can only run my code with `python ctdl/ctdl.py` instead of just `ctdl`.
Do you know why?

**Comment by ltfschoen** [comment]
I just added another commit so the files downloaded for a specific search are downloaded in the folder named specified, but always within in a 'downloads' folder of the root project directory (which is generated first if it doesn't exist. This works both when you run the ctdl.py executable from within the 'ctdl' directory (i.e. `cd ctdl; python ctdl.py`), and also when you run it from the root project directory (i.e. `python ctdl/ctdl.py`), since the `sys.path[0]` differs depending on what folder you're in when you run the executable file.

**Comment by ltfschoen** [comment]
I've also added button to toggle full screen mode, buttons to switch internationalisation language, and colour theme switching button.

**Comment by nikhilkumarsingh** [comment]
I have created a new branch "desktop-gui".
Please send pull request for that branch.

**Pull request closed without merging**
