### PR TITLE
feat: Add Flask server API with Query Parameters to configure downloads. Add screenshots.

### PR DESCRIPTION
**Pull request by ltfschoen**

### CODE REVIEW

**Comment by nikhilkumarsingh** [comment]
Considering that ctdl is a python package, I think it will be better to not incorporate flask server here. Maybe you can use server.py as a standalone script or put it in an examples folder.
Thanks.

**Comment by ltfschoen** [comment]
On my fork when I run with `ctdl` it doesn't recognise the arguments, but when I run with `python ctdl/ctdl.py` it works fine. Do you know why?
```
$ ctdl -f pdf -l 10 -minfs 10000 -maxfs 100000 -nr -p "python algorithm"
usage: ctdl [-h] [-f FILE_TYPE] [-l LIMIT] [-d DIRECTORY] [-p] [-a] [query]
ctdl: error: unrecognized arguments: -minfs -maxfs 100000 -nr python algorithm
```

**Comment by nikhilkumarsingh** [comment]
It is because  ctdl command calls the pypi ctdl package. 
If you want to test your version, you can pip install it first like this:
`sudo pip install -U .`
in your local ctdl package directory.

**Comment by ltfschoen** [comment]
Ok, I ran `pip install -U .`, and then ran `ctdl -f pdf -l 10 -minfs 10000 -maxfs 100000 -nr -p "python algorithm"`, but it gave me the following error:

```
  File "~/miniconda3/lib/python3.6/site-packages/ctdl/ctdl.py", line 9, in <module>
    from downloader import download_series, download_parallel
ModuleNotFoundError: No module named 'downloader'
```

so I opened the package file `~/miniconda3/lib/python3.6/site-packages/ctdl/ctdl.py` and manually changed it lines 9 and 10 to the following with `.` prefixes,
```
from .downloader ...
from .utils ... 
```
then it worked successfully

Do you have to update the same lines in your master repo? they don't have the `.` prefix, which may have been caused by a pull request from me earlier

**Comment by nikhilkumarsingh** [comment]
Oh yes. You should have added '.' prefixes as you are gonna use it as package now.

**Comment by ltfschoen** [comment]
@nikhilkumarsingh I have updated the Pull Request taking your feedback into account and rebased with your master branch fixing all conflicts.
I have moved the Flask server into an "examples" folder. 
I have fixed the '.' prefixes.
I have also fixed the Readme.
The idea of integrating Query Parameters using Flask is to give the option of building a front-end website GUI where the user can select the configuration from drop-downs and input fields, then click submit and it will process the download (and possibly even show the tqdm progress bar in-browser)

**Comment by ltfschoen** [comment]
@nikhilkumarsingh I fixed the following discrepencies:
 - Removed the old ctdl/server.py since we are using examples/server.py now
 - Replaced the screenshots to show calling `python examples/server.py`
 - Fixed indentation issues

**Comment by nikhilkumarsingh** [comment]
Please resolve the conflicts. Thanks.

**Comment by ltfschoen** [comment]
Conflicts resolved instead in https://github.com/nikhilkumarsingh/content-downloader/pull/14

**Pull request closed without merging**
